export const RENDER_TOKENS = {
  dpr: {
    tierA: 1.5,
    tierB: 1.5,
    tierC: 1.25,
    tierD: 1,
  },
  layout: {
    radius: 340,
    clusterRadius: 180,
    minJitter: 0.35,
    maxJitter: 1,
    goldenAngle: Math.PI * (3 - Math.sqrt(5)),
  },
  node: {
    minRadius: 3,
    maxRadius: 10,
    minDegree: 0,
    referenceDegree: 12,
    emissiveShare: 0.45,
    selectedScale: 1.2,
    hoverScale: 1.15,
    dimmedScale: 0.75,
    geometryDetail: 1,
  },
  edge: {
    minAlpha: 0.08,
    maxAlpha: 0.6,
    defaultWeight: 1,
    minWeight: 0,
    maxWeight: 5,
  },
  halo: {
    scale: 1.15,
    falloffC: 0.6,
    falloffP: 6,
    restingAlpha: 0.15,
    restingAlphaPresent: 0.35,
    selectedAlpha: 0.8,
    selectedShellFactor: 1.6,
    selectedRimPower: 2,
    selectedGeometryDetail: 3,
    maxVisible: 300,
    refreshDistance: 120,
    tierBDistance: 1600,
    tierADistance: 2200,
  },
  label: {
    fontSize: 8,
    presentScaleMultiplier: 1.8,
    offsetGap: 1.3,
    offsetPad: 2,
    maxChars: 28,
    visibleDistance: 950,
    hubBoost: 1.5,
    capTierA: 48,
    capTierB: 32,
    capTierC: 16,
    capTierD: 8,
    capPresent: 30,
    updateIntervalMs: 150,
    cameraEpsilonSq: 16,
    outlineWidthRatio: 0.08,
    renderOrder: 10,
  },
  quality: {
    emaAlpha: 0.08,
    degradeMs: 33,
    upgradeMs: 22,
    degradeFrames: 60,
    upgradeFrames: 300,
  },
  focus: {
    blendMs: 280,
    edgeDimFactor: 0.45,
    edgeDimAlphaFactor: 0.6,
    adjacentMinAlpha: 0.5,
    haloDimFactor: 0.3,
  },
  drift: {
    autoRotateSpeed: 0.25,
    presentAutoRotateSpeed: 0.2,
    idleDelayMs: 5000,
  },
  camera: {
    fov: 50,
    near: 0.1,
    far: 5000,
    initialZ: 1100,
    minDistance: 40,
    maxDistance: 3200,
    maxTargetRadius: 900,
    targetDistance: 220,
    dampingFactor: 0.08,
    dampLambda: 5,
    nearFlightDistance: 320,
    nearDurationMs: 600,
    standardDurationMs: 800,
    beatDurationMs: 1200,
    maxDurationMs: 900,
    aimLockFraction: 3,
    fitAllPaddingWorldUnits: 20,
  },
  scene: {
    fogDensity: 0.00065,
    stars: 360,
    starRadius: 1800,
    starMinBrightness: 0.35,
    starMaxBrightness: 0.9,
    keyIntensity: 0.9,
    fillIntensity: 0.5,
    ambientIntensity: 0.25,
  },
  renderLoop: {
    resizeDebounceMs: 100,
    ariaDebounceMs: 150,
  },
  time: {
    secondsToMs: 1000,
  },
} as const;

export const RENDER_COLORS = {
  keyLight: "#cfd8e6",
  fillLight: "#ffd9a8",
  fallbackKind: "#7cc8e8",
  fallbackBackgroundCenter: "#0d1017",
  fallbackBackgroundEdge: "#06080d",
  labelText: "#e6edf7",
  labelTextPresent: "#edf3fb",
  labelOutline: "#06080d",
} as const;
