export const RENDER_TOKENS = {
  dpr: {
    tierA: 1.5,
    tierB: 1.5,
    tierC: 1.25,
    tierD: 1,
  },
  layout: {
    radius: 500,
    clusterRadius: 180,
    minJitter: 0.35,
    maxJitter: 1,
    goldenAngle: Math.PI * (3 - Math.sqrt(5)),
  },
  node: {
    minRadius: 3,
    maxRadius: 10,
    minDegree: 0,
    referenceDegree: 12,
    emissiveShare: 0.45,
    selectedScale: 1.2,
    dimmedScale: 0.75,
    geometryDetail: 1,
  },
  edge: {
    minAlpha: 0.08,
    maxAlpha: 0.6,
    defaultWeight: 1,
    minWeight: 0,
    maxWeight: 5,
  },
  halo: {
    scale: 1.15,
    falloffC: 0.6,
    falloffP: 6,
    restingAlpha: 0.15,
    selectedAlpha: 0.8,
    maxVisible: 300,
    tierBDistance: 1600,
    tierADistance: 2200,
  },
  quality: {
    emaAlpha: 0.08,
    degradeMs: 33,
    upgradeMs: 22,
    degradeFrames: 60,
    upgradeFrames: 300,
  },
  camera: {
    fov: 50,
    near: 0.1,
    far: 5000,
    initialZ: 1100,
    targetDistance: 220,
    dampingFactor: 0.08,
    dampLambda: 5,
    nearDurationMs: 600,
    standardDurationMs: 800,
    maxDurationMs: 900,
    aimLockFraction: 3,
  },
  scene: {
    fogDensity: 0.0009,
    stars: 360,
    starRadius: 1800,
    starMinBrightness: 0.35,
    starMaxBrightness: 0.9,
    keyIntensity: 0.9,
    fillIntensity: 0.5,
    ambientIntensity: 0.25,
  },
  renderLoop: {
    resizeDebounceMs: 100,
    ariaDebounceMs: 150,
  },
  time: {
    secondsToMs: 1000,
  },
} as const;

export const RENDER_COLORS = {
  keyLight: "#cfd8e6",
  fillLight: "#ffd9a8",
  fallbackKind: "#7cc8e8",
  fallbackBackgroundCenter: "#0d1017",
  fallbackBackgroundEdge: "#06080d",
} as const;
