//! Queue payload records and review sidecars (ADR-005 D4 persisted formats).

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};
use serde_json::Value;

use cn_model::Timestamp;

use crate::version::{IngestError, QUEUE_RECORD_VERSION, canonical_digest, check_major};

fn current_version() -> semver::Version {
    semver::Version::parse(QUEUE_RECORD_VERSION).expect("valid const")
}

/// Submission source discriminant: remote-only fields cannot exist on an
/// in-app record by construction (ADR-005 D4).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case", tag = "kind")]
pub enum SubmissionSource {
    Remote {
        /// Claimed recipient fingerprint from the outer envelope
        /// (source_asserted routing hint).
        claimed_fingerprint: String,
        /// Outer envelope version as received.
        envelope_version: String,
        /// Fingerprint of the key that actually decrypted the box.
        key_used: String,
        /// Relay receipt id.
        receipt_id: String,
        /// Relay-reported arrival time, when available.
        relay_received_at: Option<Timestamp>,
        /// Local pull time (puller clock).
        pulled_at: Timestamp,
        /// SHA-256 over the ciphertext, computed before decryption.
        ciphertext_hash: String,
    },
    InApp {},
}

/// Immutable payload record: written once at staging, never modified.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct QueueRecord {
    /// Queue format version (unknown MAJOR rejected loudly).
    pub queue_record_version: semver::Version,
    /// Record id (UUIDv7, generated by the staging writer).
    pub record_id: String,
    /// Local staging time.
    pub staged_at: Timestamp,
    /// Source discriminant with source-specific evidence.
    pub source: SubmissionSource,
    /// The decrypted inner payload VERBATIM. Every field in here is a
    /// client assertion (source_asserted), including the consent block.
    pub payload: Value,
    /// Canonical digest of `payload`.
    pub payload_hash: String,
    /// Unknown-minor fields preserved across read/write (I7).
    #[serde(flatten)]
    pub extras: BTreeMap<String, Value>,
    /// Torn-write detection: canonical digest of this record with this
    /// field empty.
    pub record_checksum: String,
}

impl QueueRecord {
    /// Builds a record, computing payload hash and checksum.
    pub fn new(
        record_id: String,
        staged_at: Timestamp,
        source: SubmissionSource,
        payload: Value,
    ) -> Result<Self, IngestError> {
        let payload_hash = canonical_digest(&payload)?;
        let mut record = Self {
            queue_record_version: current_version(),
            record_id,
            staged_at,
            source,
            payload,
            payload_hash,
            extras: BTreeMap::new(),
            record_checksum: String::new(),
        };
        record.record_checksum = record.compute_checksum()?;
        Ok(record)
    }

    fn compute_checksum(&self) -> Result<String, IngestError> {
        let mut clone = self.clone();
        clone.record_checksum = String::new();
        canonical_digest(&clone)
    }

    /// Verifies version major, checksum, and payload hash.
    pub fn verify(&self) -> Result<(), IngestError> {
        check_major(&self.queue_record_version)?;
        if self.compute_checksum()? != self.record_checksum {
            return Err(IngestError::ChecksumMismatch {
                what: format!("queue record {}", self.record_id),
            });
        }
        if canonical_digest(&self.payload)? != self.payload_hash {
            return Err(IngestError::ChecksumMismatch {
                what: format!("payload of record {}", self.record_id),
            });
        }
        Ok(())
    }
}

/// Review state (the versioned five-state enum, ADR-005 D4).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ReviewState {
    Pending,
    ApprovedIntent,
    Approved,
    Rejected,
    /// Terminal until an explicit facilitator disposition clears it.
    Failed,
}

/// Decision-event outcome (replays write nothing; ADR-005 D4).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DecisionOutcome {
    Admitted,
    Stale,
    Illegal,
}

/// Approval-transaction event kind (never a dedup target).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TransactionKind {
    /// approved_intent -> approved, with the submit report reference.
    IntentCompleted,
    /// approved_intent -> pending: preflight denial or would-quarantine.
    PreflightFailed,
    /// approved_intent -> failed: conflicting bytes for a preassigned id.
    DurableConflict,
    /// approved_intent -> failed: impossible hole/out-of-order presence.
    DurableInconsistency,
}

/// One authoritative history schema with two event kinds (ADR-005 D4).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case", tag = "event_kind")]
pub enum HistoryEntry {
    /// A decision message's disposition - the ONLY dedup targets.
    Decision {
        decision_id: String,
        /// Canonical digest of the decision MESSAGE (a reused id with
        /// different bytes is detectable).
        message_digest: String,
        decision_type: crate::decision::DecisionType,
        prior_state: ReviewState,
        prior_generation: u64,
        resulting_state: ReviewState,
        resulting_generation: u64,
        reviewer: String,
        decided_at: Timestamp,
        reason: Option<String>,
        outcome: DecisionOutcome,
        /// Unknown-minor fields preserved across sidecar rewrites (I7).
        #[serde(flatten)]
        extras: BTreeMap<String, Value>,
    },
    /// What happened to an admitted approval AFTER admission.
    Transaction {
        linked_decision_id: String,
        kind: TransactionKind,
        prior_state: ReviewState,
        resulting_state: ReviewState,
        at: Timestamp,
        /// Submit report reference or typed failure description.
        detail: Option<String>,
        /// Unknown-minor fields preserved across sidecar rewrites (I7).
        #[serde(flatten)]
        extras: BTreeMap<String, Value>,
    },
}

/// Approval plan persisted in the approved_intent sidecar write.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ApprovalPlanRef {
    /// Preassigned op ids (UUIDv7), in batch order.
    pub op_ids: Vec<String>,
    /// Canonical per-op digests over FINAL op bytes, in batch order.
    pub per_op_digests: Vec<String>,
    /// Pre-link batch digest (ADR-005 D5 projection).
    pub batch_digest: String,
    /// The planned operations verbatim (serialized `Operation` values, in
    /// batch order). Recovery under a durable intent re-appends the absent
    /// suffix from THESE bytes: ids and digests are never regenerated
    /// (ADR-005 D4), and ids/digests alone cannot reconstruct the ops.
    pub ops: Vec<Value>,
    /// Unknown-minor fields preserved across sidecar rewrites (I7).
    #[serde(flatten)]
    pub extras: BTreeMap<String, Value>,
}

/// Mutable review-state sidecar, rewritten atomically by the native owner.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ReviewSidecar {
    /// Queue format version (unknown MAJOR rejected loudly).
    pub queue_record_version: semver::Version,
    /// Binding: the payload record's id.
    pub record_id: String,
    /// Binding: the payload record's record_checksum value.
    pub payload_digest: String,
    /// Current review state.
    pub review_state: ReviewState,
    /// Physical rewrite counter: bumps on EVERY sidecar write. Bookkeeping
    /// only - never a CAS target (ADR-005 D4, round 6).
    pub sidecar_revision: u64,
    /// Semantic decision CAS authority: advances on admitted decisions and
    /// state-changing transaction events, never on stale/illegal audit
    /// entries (replays write nothing at all).
    pub decision_generation: u64,
    /// Append-only history (decision events and transaction events).
    pub history: Vec<HistoryEntry>,
    /// Approval plan, present from approved_intent onward.
    pub plan: Option<ApprovalPlanRef>,
    /// Validation report reference for this record.
    pub validation_report: Option<String>,
    /// Unknown-minor fields preserved across rewrites (I7).
    #[serde(flatten)]
    pub extras: BTreeMap<String, Value>,
    /// Torn-write detection: canonical digest with this field empty.
    pub sidecar_checksum: String,
}

impl ReviewSidecar {
    /// Builds the initial pending sidecar for a payload record.
    pub fn initial(record: &QueueRecord) -> Result<Self, IngestError> {
        let mut sidecar = Self {
            queue_record_version: current_version(),
            record_id: record.record_id.clone(),
            payload_digest: record.record_checksum.clone(),
            review_state: ReviewState::Pending,
            sidecar_revision: 0,
            decision_generation: 0,
            history: Vec::new(),
            plan: None,
            validation_report: None,
            extras: BTreeMap::new(),
            sidecar_checksum: String::new(),
        };
        sidecar.sidecar_checksum = sidecar.compute_checksum()?;
        Ok(sidecar)
    }

    fn compute_checksum(&self) -> Result<String, IngestError> {
        let mut clone = self.clone();
        clone.sidecar_checksum = String::new();
        canonical_digest(&clone)
    }

    /// Re-seals the checksum after a mutation; every rewrite bumps the
    /// physical revision.
    pub fn seal_rewrite(&mut self) -> Result<(), IngestError> {
        self.sidecar_revision += 1;
        self.sidecar_checksum = self.compute_checksum()?;
        Ok(())
    }

    /// Verifies version major and checksum.
    pub fn verify(&self) -> Result<(), IngestError> {
        check_major(&self.queue_record_version)?;
        if self.compute_checksum()? != self.sidecar_checksum {
            return Err(IngestError::ChecksumMismatch {
                what: format!("sidecar of record {}", self.record_id),
            });
        }
        Ok(())
    }

    /// Verifies the sidecar-payload binding: filename adjacency is not an
    /// integrity binding (ADR-005 D4).
    pub fn verify_pair(&self, record: &QueueRecord) -> Result<(), IngestError> {
        self.verify()?;
        record.verify()?;
        if self.record_id != record.record_id || self.payload_digest != record.record_checksum {
            return Err(IngestError::BindingMismatch {
                record_id: self.record_id.clone(),
            });
        }
        Ok(())
    }
}
