// @ts-ignore wasm-pack output is generated by the core build step.
import init, { CnApi } from "../../core/crates/cn-wasm/pkg/cn_wasm.js";

const groupId = "00000000-0000-0000-0000-000000000010";
const viewer = JSON.stringify({ kind: "anonymous" });
const template = JSON.stringify({
  schema_version: "0.1.0",
  template_id: "research",
  name: "Research Network",
  description: "Synthetic research network",
  kinds: [
    {
      id: "person",
      label: "Person",
      shape: "sphere",
      color_role: "kind-1",
      attributes: [{ id: "display_name", type: "text", required: true }],
    },
  ],
  edge_kinds: [
    {
      id: "knows",
      label: "Knows",
      from: ["person"],
      to: ["person"],
      directed: false,
      weighted: "forbidden",
    },
  ],
  theme: { mode: "light", roles: { "kind-1": "#224466" } },
});

type Step = {
  name: string;
  pass: boolean;
  json: string;
};

const results = document.querySelector<HTMLDivElement>("#results");

function parseEnvelope(json: string): unknown {
  const parsed = JSON.parse(json) as { ok?: unknown; err?: unknown };
  if ("err" in parsed) {
    throw new Error(JSON.stringify(parsed.err));
  }
  return parsed.ok;
}

function render(steps: Step[]): void {
  if (!results) {
    return;
  }
  results.replaceChildren(
    ...steps.map((step) => {
      const section = document.createElement("section");
      const status = document.createElement("div");
      status.className = step.pass ? "pass" : "fail";
      status.textContent = `${step.pass ? "PASS" : "FAIL"} ${step.name}`;
      const pre = document.createElement("pre");
      pre.textContent = step.json;
      section.append(status, pre);
      return section;
    }),
  );
}

async function run(): Promise<void> {
  await init();
  const api = new CnApi();
  const steps: Step[] = [];
  for (const [name, call] of [
    ["core_info", () => api.core_info()],
    ["load_group_begin", () => api.load_group_begin(groupId, viewer, template)],
    ["load_group_commit", () => api.load_group_commit(groupId, Date.now())],
    ["projection", () => api.projection(groupId, viewer)],
  ] as const) {
    try {
      const json = call();
      parseEnvelope(json);
      steps.push({ name, pass: true, json });
    } catch (err) {
      steps.push({
        name,
        pass: false,
        json: err instanceof Error ? err.message : String(err),
      });
    }
  }
  render(steps);
}

run().catch((err: unknown) => {
  render([
    {
      name: "smoke",
      pass: false,
      json: err instanceof Error ? err.message : String(err),
    },
  ]);
});
